/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_mantou_jvmti4j_JVMTIScheduler */

#ifndef _Included_me_mantou_jvmti4j_JVMTIScheduler
#define _Included_me_mantou_jvmti4j_JVMTIScheduler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_mantou_jvmti4j_JVMTIScheduler
 * Method:    retransformClass0
 * Signature: (Ljava/lang/Class;)I
 */
JNIEXPORT jint JNICALL Java_me_mantou_jvmti4j_JVMTIScheduler_retransformClass0
  (JNIEnv *, jclass, jclass);

/*
 * Class:     me_mantou_jvmti4j_JVMTIScheduler
 * Method:    getLoadedClasses
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_me_mantou_jvmti4j_JVMTIScheduler_getLoadedClasses
  (JNIEnv *, jclass);

/*
 * Class:     me_mantou_jvmti4j_JVMTIScheduler
 * Method:    getClassLoaderClasses
 * Signature: (Ljava/lang/ClassLoader;)[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_me_mantou_jvmti4j_JVMTIScheduler_getClassLoaderClasses
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
